package Nov13_Day10;
public class HelloPrint {
	public static String hello()
	{
		return "Hello ";
	}
	public static String programmer()
	{
		 return " I AM JAVA PROGRAMMER";
	}
	public static String generated()
	{
		return ",THIS MESSAGE IS GENERATED BY STATIC METHOD CALLS" ;
	}
	public static void main(String[] args)
	{
		System.out.println(hello()+programmer()+generated());
	}
 
}
